spring:
    datasource:
      url: jdbc:h2:tcp://localhost/~/datajpa
      username: sa
      password:
      driver-class-name: org.h2.Driver
    jpa:
        hibernate:
                ddl-auto: create
        properties:
                hibernate:
                show_sql: true
                format_sql: true
        logging.level:
    data:
      web:
        pageable:
          default-page-size: 10
          max-page-size: 2000
          one-indexed-parameters: true # page 1부터 시작한다
org.hibernate.SQL: debug  # 로그냄긴다
  #  org.hibernate.type: trace